### ISSUE TITLE
Dokumentace view 

### ISSUE THREAD

**Issue by JindrichPilar** [fit-fms/fms#21]
Je potreba doplnit zakladni dokumentaci.

Bylo by dobre pri tom zkontrolovat jak to sedi s navrhovou dokumentaci. _[implementace musí odpovídat návrhu, případně je NUTNE návrhovou dokumentaci upravit](https://edux.fit.cvut.cz/courses/BI-SI1/tutorials/start#napln_cviceni)_  
Tady si myslim ze to bude 100% potreba kdyz jsme GWT zahodili. Nicmene asi uprava bude spocivat v tom ze se smaze vsechno okolo GWT, doda se tam ta trida co parsuje Form z HTTP a do popisu balicku se rekne ze se pouzije jtwig.
- Balicku
  - Jaky typ problemu resi.
- Trid
  - Co dela
- Metod
  - Co metoda dela (pr: `Zobrazi prazdy formular k vyplneni`)
  - Obsah promennych (pr: `@param archetype jmeno archetypu k zobrazeni`)
  - Exception (V jakych pripade hazi exception - chyba vs NotFound je asi nejdulezitejsi)
  - Co vraci (U kontrolleru pr: `Nazev sablony`) 

[Priklad](http://www.docjar.net/html/api/java/util/Collections.java.html)

**Comment by grissius** [comment]
Doplnil jsem dokumentaci k tridam co maji co delat s view. V EA to predelam zitra.

**Comment by JindrichPilar** [comment]
Ok. Az to budes mit tak tu issue zavri.

**Comment by grissius** [comment]
Predelal jsem View v EA, doplnil/upravil jsem snad dobre i ty tridy, ktere jsme neimplementovali.
